### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/CommonRLSpaces.jl#5]
- [ ] Make sure the concept of `Space` is applicable to all the environments defined in `RLEnvs`
- [ ] Check whether it is applicable to some other packages:
  - [ ] POMDPs.jl
  - [ ] AlphaZero.jl
  - [ ] Dojo.jl
- [ ] Move this into `CommonRLInterface`

**Comment by findmyway** [comment]
@JuliaRegistrator register

**Comment by jeremiahpslewis** [comment]
@JuliaRegistrator register
